# Generated by Django 4.2.4 on 2023-08-15 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainApp", "0003_alter_product_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="stock",
            field=models.BooleanField(default=True),
        ),
    ]
