# Generated by Django 4.2.4 on 2023-08-18 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainApp", "0006_alter_buyer_pin"),
    ]

    operations = [
        migrations.AddField(
            model_name="buyer",
            name="phone",
            field=models.CharField(default="", max_length=15),
        ),
    ]
