# Generated by Django 4.2.4 on 2023-08-30 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainApp", "0011_testimonial"),
    ]

    operations = [
        migrations.AddField(
            model_name="buyer",
            name="otp",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
